export {
  DISTORTION_STATES,
  DISTORTION_THRESHOLDS,
  getDistortionStatesForScore,
  getPrimaryDistortionState,
  hasDistortionState,
  inspectDistortion,
  interpretDistortion,
  isDistortionState,
  mergeDistortionStates,
  normalizeDistortionStates,
  propagateDistortion,
  resolveDistortionStates,
  type DistortionCarrier,
  type DistortionInsight,
  type DistortionInput,
  type DistortionState,
  type DistortionThresholds,
} from './shared/distortion'
