export {
  CONSEQUENCE_LADDERS,
  OUTCOME_EXPLANATIONS,
  OUTCOME_THRESHOLDS,
  SEVERE_HIT_TABLES,
  assertExclusiveOutcomeBuckets,
  clampOutcomeValue,
  describeConsequenceRoute,
  explainOutcome,
  getConsequenceLadder,
  getConsequencesForBand,
  getOutcomeBand,
  getSevereHitOutcomes,
  getSevereHitTable,
  mapResolutionResultToExclusiveOutcome,
  recordExclusiveOutcome,
  resolveConsequenceRoute,
  resolveContest,
  type ConsequenceKey,
  type ConsequenceLadder,
  type ConsequenceRoute,
  type ContestResolution,
  type ContestResolutionInput,
  type ExclusiveOutcomeType,
  type OutcomeBand,
  type OutcomeThresholds,
  type SevereHitTable,
} from './shared/outcomes'

export type { ThreatFamily } from './shared/modifiers'
