export {
  CONDITIONS,
  TAGS,
  appendUniqueTags,
  attachCondition,
  attachTags,
  createTagSet,
  getCondition,
  getTagsByFamily,
  hasAllTags,
  hasAnyTag,
  hasTag,
  isConditionAllowedFor,
  isValidTagKey,
  mergeTags,
  type CanonicalTag,
  type ConditionCarrierKind,
  type ConditionDefinition,
  type ConditionKey,
  type TagFamily,
} from './shared/tags'
