import { type CaseTemplate } from '../models'

export const occultCaseTemplates: CaseTemplate[] = [
  {
    templateId: 'occult-001',
    title: 'Black Candle Synod',
    description:
      'A sealed chapel is lit from within by a ring of black candles. The rite is drawing in active personnel and must be broken before the congregation finishes the chant.',
    mode: 'threshold',
    kind: 'case',
    difficulty: { combat: 24, investigation: 44, utility: 30, social: 26 },
    weights: { combat: 0.2, investigation: 0.35, utility: 0.2, social: 0.25 },
    durationWeeks: 2,
    deadlineWeeks: 2,
    tags: ['occult', 'ritual', 'chapel', 'tier-2'],
    requiredTags: ['occultist'],
    preferredTags: ['holy', 'negotiator', 'ritual-kit'],
    raid: { minTeams: 2, maxTeams: 3 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 1 },
      spawnTemplateIds: ['combat-001', 'raid-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 2,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['raid-001'],
      convertToRaidAtStage: 4,
    },
  },
  {
    templateId: 'occult-002',
    title: 'Funeral Choir Echo',
    description:
      'Grief recordings are looping through a municipal memorial system. Responders hear their own names in the mix, then lose time.',
    mode: 'probability',
    kind: 'case',
    difficulty: { combat: 12, investigation: 54, utility: 28, social: 34 },
    weights: { combat: 0.1, investigation: 0.45, utility: 0.2, social: 0.25 },
    durationWeeks: 3,
    deadlineWeeks: 3,
    tags: ['occult', 'resonance', 'memorial', 'tier-2'],
    requiredTags: ['scholar'],
    preferredTags: ['scholar', 'negotiator'],
    raid: { minTeams: 2, maxTeams: 3 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-003', 'bio-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 2,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-007', 'psi-occ-001', 'occult-008'],
      convertToRaidAtStage: 3,
    },
  },
  {
    templateId: 'occult-003',
    title: 'Mirror-Line Exorcism',
    description:
      'Reflections in the lobby glass are moving half a second late. The entity is vulnerable to ritual interference, but only if the line is held under pressure.',
    mode: 'deterministic',
    kind: 'case',
    difficulty: { combat: 20, investigation: 38, utility: 24, social: 30 },
    weights: { combat: 0.15, investigation: 0.4, utility: 0.2, social: 0.25 },
    durationWeeks: 2,
    deadlineWeeks: 2,
    tags: ['occult', 'mirror', 'possession', 'tier-2'],
    requiredTags: ['holy'],
    preferredTags: ['investigator', 'tech', 'ritual-kit'],
    raid: { minTeams: 2, maxTeams: 4 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 1 },
      spawnTemplateIds: ['combat-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['raid-001', 'occult-004'],
      convertToRaidAtStage: 4,
    },
  },
  {
    templateId: 'occult-004',
    title: 'Saintly Ashen Vault',
    description:
      'A reliquary vault is leaking ash that reacts to speech. Teams must suppress the rite and secure the relic before the vault starts answering back.',
    mode: 'threshold',
    kind: 'raid',
    difficulty: { combat: 30, investigation: 40, utility: 42, social: 22 },
    weights: { combat: 0.2, investigation: 0.3, utility: 0.3, social: 0.2 },
    durationWeeks: 4,
    deadlineWeeks: 2,
    tags: ['occult', 'reliquary', 'vault', 'tier-2'],
    requiredTags: ['holy'],
    preferredTags: ['tech', 'medic'],
    raid: { minTeams: 2, maxTeams: 4 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-005', 'info-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 2,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['raid-001'],
    },
  },
  {
    templateId: 'occult-005',
    title: 'Cathedral Under Glass',
    description:
      'A greenhouse chapel contains a weather system that only answers to liturgy. If the hymn breaks, the structure converts into a hostile containment node.',
    mode: 'deterministic',
    kind: 'case',
    difficulty: { combat: 18, investigation: 32, utility: 34, social: 36 },
    weights: { combat: 0.1, investigation: 0.25, utility: 0.3, social: 0.35 },
    durationWeeks: 2,
    deadlineWeeks: 3,
    tags: ['occult', 'weather', 'cathedral', 'tier-2'],
    requiredTags: ['scholar'],
    preferredTags: ['tech', 'negotiator'],
    raid: { minTeams: 2, maxTeams: 3 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 1 },
      spawnTemplateIds: ['occult-006'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 2,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-007', 'psi-occ-001'],
      convertToRaidAtStage: 4,
    },
  },
  {
    templateId: 'occult-006',
    title: 'Red Lantern Procession',
    description:
      'An impossible parade is crossing restricted streets at dusk. Witnesses follow the lanterns until they vanish into the crowd and reappear as numbered omens.',
    mode: 'probability',
    kind: 'case',
    difficulty: { combat: 14, investigation: 26, utility: 22, social: 40 },
    weights: { combat: 0.15, investigation: 0.2, utility: 0.15, social: 0.5 },
    durationWeeks: 3,
    deadlineWeeks: 2,
    tags: ['occult', 'parade', 'social', 'tier-2'],
    requiredTags: ['negotiator'],
    preferredTags: ['medium', 'investigator'],
    raid: { minTeams: 2, maxTeams: 4 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-001', 'combat-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['raid-001', 'occult-004'],
      convertToRaidAtStage: 3,
    },
  },
  {
    templateId: 'occult-007',
    title: 'Crypt Bell Cataclysm',
    description:
      'A sealed catacomb chapel beneath the old quarter is tolling a bell that has no physical striker. ' +
      'Each ring marks a radius where spoken vows become binding compulsions, and responders have already begun repeating liturgical fragments involuntarily.' +
      ' Teams must shut down the bell locus and recover the reliquary core before the compulsion zone expands into adjacent wards.',
    mode: 'threshold',
    kind: 'raid',
    difficulty: { combat: 34, investigation: 36, utility: 30, social: 24 },
    weights: { combat: 0.25, investigation: 0.3, utility: 0.25, social: 0.2 },
    durationWeeks: 3,
    deadlineWeeks: 2,
    tags: ['occult', 'catacomb', 'raid', 'tier-3'],
    requiredTags: ['holy', 'scholar'],
    preferredTags: ['ritual-kit', 'tech', 'medic'],
    raid: { minTeams: 2, maxTeams: 4 },
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-004', 'raid-001'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 2,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['raid-001'],
    },
  },
  {
    templateId: 'occult-008',
    title: 'Pilgrim Signal Litany',
    description:
      'A rotating group of civilians is broadcasting identical devotional phrases on emergency radio bands at precise nineteen-minute intervals. ' +
      'The litany appears benign until listeners repeat it aloud, after which they begin following route instructions toward a closed shrine district.' +
      ' Teams must break the transmission pattern and stabilize affected civilians before the route converges into a mass-ritual formation.',
    mode: 'probability',
    kind: 'case',
    difficulty: { combat: 10, investigation: 30, utility: 20, social: 34 },
    weights: { combat: 0.1, investigation: 0.3, utility: 0.2, social: 0.4 },
    durationWeeks: 2,
    deadlineWeeks: 2,
    tags: ['occult', 'ritual', 'civilian', 'tier-2'],
    preferredTags: ['negotiator', 'medium', 'holy'],
    pressureValue: 8,
    regionTag: 'occult_district',
    onFail: {
      stageDelta: 1,
      spawnCount: { min: 1, max: 1 },
      spawnTemplateIds: ['occult-006'],
    },
    onUnresolved: {
      stageDelta: 2,
      deadlineResetWeeks: 1,
      spawnCount: { min: 1, max: 2 },
      spawnTemplateIds: ['occult-007', 'psi-occ-001'],
    },
  },
]
