export const APP_ROUTES = {
  operationsDesk: '/',
  dashboard: '/',
  help: '/help',
  agents: '/agents',
  cards: '/cards',
  agentDetail: (agentId: string) => `/agents/${encodeURIComponent(agentId)}`,
  recruitment: '/recruitment',
  registry: '/registry',
  registryDetail: (agentId: string) => `/registry/${encodeURIComponent(agentId)}`,
  contracts: '/contracts',
  cases: '/cases',
  caseDetail: (caseId: string) => `/cases/${encodeURIComponent(caseId)}`,
  teams: '/teams',
  teamDetail: (teamId: string) => `/teams/${encodeURIComponent(teamId)}`,
  trainingDivision: '/training-division',
  equipment: '/equipment',
  fabrication: '/fabrication',
  containmentSite: '/containment-site',
  marketsSuppliers: '/markets-suppliers',
  factions: '/factions',
  rankings: '/rankings',
  agency: '/agency',
  report: '/report',
  reportDetail: (week: number | string) => `/report/${week}`,
  intel: '/intel',
  intelDetail: (templateId: string) => `/intel/${encodeURIComponent(templateId)}`,
} as const

export const APP_ROUTE_PATTERNS = {
  agentDetail: '/agents/:agentId',
  registryDetail: '/registry/:agentId',
  caseDetail: '/cases/:caseId',
  teamDetail: '/teams/:teamId',
  reportDetail: '/report/:week',
  intelDetail: '/intel/:templateId',
} as const
