export const DEPARTMENT_WORKSHOP_ACTIVATION_UI_TEXT = {
  pageEyebrow: 'Workshop command',
  pageHeading: 'Activate department workshop',
  pageSubtitle:
    'Select a completed construction case and structural route to activate one empty department workshop.',
  backToMirrorLabel: 'Back to workshop mirror',
  backToDeskLabel: 'Back to Operations Desk',
  mirrorLinkLabel: 'Activate workshop',
  departmentLabel: 'Department',
  caseAndRouteLabel: 'Construction case / structural route',
  slotCapacityLabel: 'Slot capacity',
  slotCapacityHint: 'Positive integer. Determines how many work orders can be active simultaneously.',
  submitLabel: 'Activate workshop',
  alreadyActivatedNote: 'This department already has an activated workshop.',
  emptyTitle: 'No eligible construction cases',
  emptyBody:
    'A department workshop can only be activated after a construction case reaches full completion and has structural routes in its map layer. Complete an SPE-110 construction case first.',
  allActivatedTitle: 'All department workshops are active',
  allActivatedBody:
    'Every registered department already has an active workshop. Use the workshop mirror to inspect current capacity and queued work.',
  resultActivatedLabel: 'Workshop activated.',
  resultUnchangedLabel: 'Workshop already active with identical capacity — no change.',
  resultBlockedLabel: 'Activation blocked.',
  reasonInvalidRequest: 'Invalid activation request — check department, case, route, and slot capacity.',
  reasonInvalidDepartmentRegistry: 'Department registry validation failed.',
  reasonMissingDepartment: 'Department not found in capability registry.',
  reasonMissingCase: 'Construction case not found.',
  reasonConstructionIncomplete: 'Construction is not yet complete for this case.',
  reasonMissingMapLayer: 'No map layer or routes found on this case.',
  reasonMissingRoute: 'Structural route not found in this case\'s map layer.',
  reasonAlreadyActive: 'This department already has an active workshop snapshot.',
  reasonInvalidWorkshopState: 'Workshop state validation failed — possible data integrity issue.',
  reasonUnknown: 'Activation blocked for an unknown reason.',
} as const
