// cspell:words blacksite psionic stabilised
import {
  type AgentRole,
  type CaseMode,
  type CaseStatus,
  type StatKey,
  type TeamCoverageRole,
} from '../domain/models'
import {
  createDeterministicReportNote,
  formatEscalatedCaseNoteContent,
  formatFailedCaseNoteContent,
  formatPartialCaseNoteContent,
  formatRaidConvertedNoteContent,
  formatResolvedCaseNoteContent,
  formatSpawnFollowUpNoteContent,
  formatWeekDeltaNoteContent,
} from '../domain/reportNotes'
import { agentClassTables } from '../domain/templates/classTables'

/**
 * Display labels for agent roles.
 */
export const ROLE_LABELS: Record<AgentRole, string> = {
  hunter: agentClassTables.hunter.label,
  occultist: agentClassTables.occultist.label,
  investigator: agentClassTables.investigator.label,
  field_recon: agentClassTables.field_recon.label,
  medium: agentClassTables.medium.label,
  tech: agentClassTables.tech.label,
  medic: agentClassTables.medic.label,
  negotiator: agentClassTables.negotiator.label,
}

export const ROLE_COVERAGE_LABELS: Record<TeamCoverageRole, string> = {
  containment: 'Containment',
  investigator: 'Investigator',
  support: 'Support',
  tactical: 'Tactical',
  technical: 'Technical',
}

/**
 * Display labels for case resolution modes.
 */
export const MODE_LABELS: Record<CaseMode, string> = {
  threshold: 'Threshold',
  probability: 'Probability',
  deterministic: 'Deterministic',
  standard: 'Standard',
}

/**
 * Display labels for case status.
 */
export const STATUS_LABELS: Record<CaseStatus, string> = {
  open: 'Open',
  in_progress: 'Active',
  resolved: 'Resolved',
}

/**
 * Display labels for skill/stat categories.
 */
export const STAT_LABELS: Record<StatKey, string> = {
  combat: 'Combat',
  investigation: 'Investigation',
  utility: 'Utility',
  social: 'Social',
}

/**
 * Tooltip text for UI elements.
 */
export const TOOLTIPS: Record<string, string> = {
  'mode.threshold':
    'Resolution is deterministic: your deployed team must meet or exceed the operation threshold.',
  'mode.probability':
    'Resolution uses a probability curve. Higher score improves odds but never guarantees success.',
  'mode.deterministic':
    'Resolution is gated by required capabilities. Team composition and tags decide viability.',
  'stat.combat': 'Effectiveness in direct confrontation and tactical engagement.',
  'stat.investigation': 'Skill in gathering information, analysis, and evidence processing.',
  'stat.utility': 'Practical capability with tools, equipment, and problem-solving.',
  'stat.social': 'Effectiveness in communication, negotiation, and interpersonal influence.',
  'case.stage':
    'Escalation level (1–5). Higher stage raises difficulty, pressure, and follow-up spawn risk.',
  'case.deadline': 'Weeks before the operation auto-escalates if left unresolved.',
  'case.duration': 'Weeks required to complete the operation after assignment.',
  'case.weeksRemaining': 'Weeks left before the assigned team finishes.',
  'case.bestOdds': 'Estimated success probability for the strongest available assignment option.',
  'team.fatigue':
    'Operational strain accumulated from active deployments. Reduces effective output.',
  'team.chemistry': 'Relationship bonus or penalty generated by agent pairings.',
  'agent.role': 'Agency specialization that defines core strengths and capability tags.',
  'case.lore': 'Narrative intelligence hook for this operation. Flavor only, no mechanical effect.',
  'report.notes': 'Timeline of events generated during this week. Useful for post-op review.',
}

/**
 * Navigation route labels used across pages.
 */
export const NAVIGATION_ROUTES = {
  operationsDesk: { to: '/', label: 'Operations Desk' },
  agents: { to: '/agents', label: 'Agents' },
  recruitment: { to: '/recruitment', label: 'Recruitment' },
  cards: { to: '/cards', label: 'Party Cards' },
  registry: { to: '/registry', label: 'Registry' },
  teams: { to: '/teams', label: 'Teams' },
  trainingDivision: { to: '/training-division', label: 'Training Division' },
  equipment: { to: '/equipment', label: 'Equipment' },
  fabrication: { to: '/fabrication', label: 'Fabrication' },
  cases: { to: '/cases', label: 'Cases' },
  containmentSite: { to: '/containment-site', label: 'Containment Site' },
  marketsSuppliers: { to: '/markets-suppliers', label: 'Markets / Suppliers' },
  factions: { to: '/factions', label: 'Factions' },
  rankings: { to: '/rankings', label: 'Rankings' },
  agency: { to: '/agency', label: 'Agency' },
  report: { to: '/report', label: 'Reports' },
  intel: { to: '/intel', label: 'Intel' },
}

/**
 * Dashboard stat card labels.
 */
export const DASHBOARD_STAT_LABELS: Record<string, string> = {
  open: 'Pending Operations',
  inProgress: 'Active Deployments',
  resolved: 'Cases Resolved',
  score: 'Breach Score',
  avgFatigue: 'Team Fatigue / Avg Fatigue',
  maxStage: 'Highest Stage',
  deadlineRisk: 'Deadline Risk Cases',
  criticalStage: 'Critical Stage Cases',
  raidUnderstaffed: 'Understaffed Raids',
  overstretchedTeams: 'Overstretched Teams',
  seed: 'Seed',
  rngState: 'RNG State',
}

/**
 * Dashboard action/button labels.
 */
export const DASHBOARD_ACTIONS: Record<string, string> = {
  advanceWeek: 'Advance Week →',
  reset: 'Reset',
  copySeed: 'Copy Seed',
  newSeed: 'New Seed',
  exportRun: 'Export Run',
  importRun: 'Import Run',
  newRunFromCurrentConfig: 'New Run From Current Config',
}

/**
 * Dashboard balance preset labels.
 */
/**
 * Dashboard reset confirmation copy.
 */
export const DASHBOARD_CONFIRM: Record<string, string> = {
  resetPrompt: 'Reset to Week 1?',
  confirmReset: 'Confirm Reset',
  cancelReset: 'Cancel',
}

/**
 * Cases page filter and triage copy.
 */
export const CASES_FILTER_TEXT: Record<string, string> = {
  riskFilterLabel: 'At-risk only',
  riskFilterActive: 'At-risk',
  riskFilterTooltip:
    'Show only open/active cases with deadline risk, Stage 4+, role/tag coverage blocks, or no assignment at Stage 2+.',
}

/**
 * Dashboard balance preset labels.
 */
export const DASHBOARD_PRESET_LABELS: Record<string, string> = {
  forgiving: 'Forgiving',
  standard: 'Standard',
  nightmare: 'Nightmare',
}

/**
 * Dashboard section headers.
 */
export const DASHBOARD_SECTIONS: Record<string, string> = {
  simulationControls: 'Simulation Controls',
  operationsFeed: 'Operations Feed',
  fieldStatus: 'Field Status',
  advisory: 'Advisory / Analysis',
  fabrication: 'Fabrication Queue',
  market: 'Resource Market',
  performance: 'Performance Metrics',
  latestReport: 'Latest Report',
  runTransfer: 'Run Transfer',
}

/**
 * Dashboard headline and status copy.
 */
export const DASHBOARD_HEADLINE = {
  title: 'Containment Protocol',
  weekLabel: 'Week {week} / Active cap {cap}',
  haltedPrefix: 'Simulation halted:',
}

/**
 * Feedback messages for dashboard actions.
 */
export const FEEDBACK_MESSAGES: Record<string, string> = {
  seedCopied: 'Seed copied.',
  seedUnavailable: 'Copy unavailable.',
  seedInfo: 'Seed can be shared for reproducible runs.',
  runExportReady: 'Run payload ready.',
  runImported: 'Run imported.',
  runImportInvalid: 'Import failed.',
  runStartedFromCurrentConfig: 'Fresh run started from current config.',
}

/**
 * Empty-state and placeholder text.
 */
export const EMPTY_STATES: Record<string, string> = {
  noReports: 'No reports yet. Advance a week to begin the run.',
  noEvents:
    'No operational events yet. Assign a team or advance the week to generate simulation output.',
  noEventMatches: 'No operational events match the current filters.',
  noUrgentCasePressure: 'No urgent case pressure right now.',
  noAtRiskTeams: 'No stressed teams are currently flagged.',
  noAssignment: 'Unassigned',
  noAgentsMatch: 'No agents match the current filters.',
  noRegistryMatches: 'No personnel match the current search.',
}

export const EVENT_FEED_TEXT = {
  subtitle: 'Unified simulation output from assignment, incident, intel, and future queue systems.',
  searchLabel: 'Search feed',
  searchPlaceholder: 'Search cases, teams, agents, or summaries',
  categoryLabel: 'Category',
  sourceLabel: 'Source',
  typeLabel: 'Type',
  weekMinLabel: 'Week from',
  weekMaxLabel: 'Week to',
  entityIdLabel: 'Entity ID',
  entityIdPlaceholder: 'case-001, t_nightwatch, a_ava…',
  allCategories: 'All categories',
  allSources: 'All systems',
  allTypes: 'All event types',
  relationshipVerbosityLabel: 'Relationship events',
  relationshipSummaryMode: 'Summary by pair',
  relationshipAllMode: 'All relationship updates',
  showingResults: 'Showing {count} of {total} events',
}

export const OPERATIONS_DESK_TEXT = {
  directorSectionLabel: 'Operations directorate',
  directorName: 'Command authority online. Cross-division readiness is stable.',
  traitsLabel: 'Directorate posture',
  fieldIntelLabel: 'Field intel',
  fabricationOrdersLabel: 'Fabrication orders',
  reserveStaffLabel: 'Reserve staff',
  fieldIntelActivePrefix: 'Latest intel report week',
  fieldIntelNone: 'No intel report generated yet.',
  queueIdleLabel: 'Queue capacity available.',
  queuePressurePrefix: 'Queue pressure',
  fieldStatusSubtitle:
    'Live unit posture: assignments, case progress, remaining time, and readiness.',
  advisorySubtitle:
    'Read-only staff and system guidance. Recommendations do not block weekly resolution or MVP flow.',
  fabricationSubtitle:
    'Start equipment production now; completion resolves on weekly ticks and writes to the event feed.',
  marketSubtitle:
    'Weekly supply pressure changes fabrication cost and the featured recipe discount.',
  performanceSubtitle:
    'Run-level output from the current campaign: resolution rate, throughput, and pressure.',
  agentsLabel: 'Agents',
  assignedCaseLabel: 'Assigned case',
  progressLabel: 'Progress',
  remainingLabel: 'Time remaining',
  statusLabel: 'Status',
  noAdvisories: 'No advisory flags right now. Operations can proceed without this layer.',
  openCaseAction: 'Open case',
  openTeamAction: 'Open team',
  openAgentAction: 'Open agent',
  idleStatus: 'Idle',
  deployingStatus: 'Deploying',
  recoveringStatus: 'Recovering',
  overstretchedStatus: 'Overstretched',
  noQueue: 'No fabrication orders active.',
  queueAction: 'Queue',
  featuredRecipe: 'Featured',
  supplyPressure: 'Supply pressure',
  costMultiplier: 'Cost multiplier',
  resolutionRate: 'Resolution rate',
  queueThroughput: 'Queue throughput',
  activePressure: 'Active pressure',
  fabricatedStock: 'Fabricated stock',
}

/**
 * Fabrication page copy.
 */
export const FABRICATION_UI_TEXT = {
  pageHeading: 'Fabrication Lab',
  pageSubtitle:
    'Deterministic assembly queue for field tools, containment kits, and laboratory output.',
  queueCountLabel: 'Queue',
  remainingWeeksLabel: 'Remaining queue weeks',
  completedOrdersLabel: 'Completed orders',
  marketPressureLabel: 'Market pressure',
  recipeCatalogHeading: 'Fabrication recipes',
  queueButton: 'Queue',
  activeQueueHeading: 'Active lab queue',
  noActiveOrders: 'No active orders.',
  remainingWeeksSuffix: 'w remaining',
  outputLabel: 'Output',
  inventoryHeading: 'Finished stock',
}

/**
 * Market page copy.
 */
export const MARKET_UI_TEXT = {
  pageHeading: 'Market',
  pageSubtitle:
    'Deterministic supply channels for field gear, laboratory components, and containment materials. Prices shift weekly with supply pressure.',
  pressureLabel: 'Market pressure',
  multiplierLabel: 'Price multiplier',
  featuredLabel: 'Featured line',
  availableFundingLabel: 'Available funding',
  buyOne: 'Buy 1 bundle',
  buyThree: 'Buy 3 bundles',
  orderOne: 'Order supplier delivery (1 bundle)',
  orderThree: 'Order supplier delivery (3 bundles)',
  delayedDeliveryBlocked: 'Supplier delivery only — instant exchange unavailable for this line.',
  redeemFavorOne: 'Redeem favor (1 bundle)',
  redeemFavorThree: 'Redeem favor (3 bundles)',
  callObligationOne: 'Call obligation (1 bundle)',
  callObligationThree: 'Call obligation (3 bundles)',
  sellOne: 'Sell 1 bundle',
  sellThree: 'Sell 3 bundles',
  noListings: 'No listings match the current filters.',
  transactionLogHeading: 'Current week procurement log',
  noTransactions: 'No current-week transactions recorded.',
  exhaustedListing: 'Listing exhausted',
  insufficientFundingBy: 'Need +{amount}',
  noSellStock: 'No matching stock available to sell.',
}

export const MARKET_SOURCE_LABELS = {
  recipe: 'Recipe',
  material: 'Material',
  direct_equipment: 'Equipment',
} as const

/**
 * Registry page copy.
 */
export const REGISTRY_UI_TEXT = {
  pageHeading: 'Registry',
  pageSubtitle: 'Personnel records across field assignments and reserve staffing.',
  reserveStaffLabel: 'Reserve staff',
  shownLabel: 'shown',
  totalLabel: 'total',
  searchLabel: 'Search',
  searchPlaceholder: 'Search by name, role, tags, or team',
  filterRoleLabel: 'Role',
  allRolesLabel: 'All roles',
  filterStatusLabel: 'Status',
  filterTeamLabel: 'Team',
  allTeamsLabel: 'All teams',
  reserveOnlyLabel: 'Reserve only',
  filterFatigueLabel: 'Fatigue',
  sortLabel: 'Sort',
  clearFiltersLabel: 'Clear filters',
  trainingStatus: 'Training',
  fieldTeamStatus: 'Field team',
  reserveStatus: 'Reserve',
  allStatusesLabel: 'All statuses',
  activeLabel: 'Active',
  injuredLabel: 'Injured',
  recoveringLabel: 'Recovering',
  deadLabel: 'Dead',
  allFatigueBandsLabel: 'All fatigue bands',
  steadyLabel: 'Steady',
  strainedLabel: 'Strained',
  criticalLabel: 'Critical',
  sortByNameLabel: 'Name',
  sortByFatigueLabel: 'Fatigue',
  sortByStatusLabel: 'Status',
  sortByTeamLabel: 'Team',
  teamLabel: 'Team',
  reservePoolLabel: 'Reserve Pool',
  operationalStateLabel: 'Operational state',
  fatigueLabel: 'Fatigue',
  tagsLabel: 'Tags',
  noTagsLabel: 'None',
}

/**
 * Config field labels and options.
 */
export const CONFIG_FIELDS: Record<string, string> = {
  seed: 'Seed',
  stageScalar: 'Stage Scalar',
  partialMargin: 'Partial Margin',
  activeCap: 'Active Cap',
  attritionPerWeek: 'Attrition / Week',
  probabilityK: 'Probability K',
  raidTeamPenalty: 'Raid Team Penalty',
  durationModel: 'Duration Model',
  durationModelCapacity: 'Capacity Focus',
  durationModelAttrition: 'Attrition Pressure',
  durationModelLockedHint: 'Apply Nightmare to unlock attrition pressure for challenge runs.',
  durationModelUnlockedHint:
    'Challenge mode is active. Attrition pressure makes long operations harder each week.',
  presetHint:
    'Forgiving and Standard keep duration readable. Nightmare unlocks harsher attrition pressure.',
}

/**
 * Report/score display labels.
 */
export const REPORT_LABELS: Record<string, string> = {
  week: 'Week',
  points: 'pts',
  new: 'New',
  progressed: 'Progressed',
  partial: 'Partial',
  resolved: 'Resolved',
  unresolved: 'Unresolved',
  spawned: 'Spawned',
  failed: 'Failed',
  avgFatigue: 'Avg Fatigue',
  maxStage: 'Max Stage',
  rngBefore: 'RNG Before',
  rngAfter: 'RNG After',
  cumulativeScore: 'Cumulative Score',
  unresolvedTriggers: 'Unresolved Trigger',
}

/**
 * Case assignment and team UI labels.
 */
export const CASE_UI_LABELS: Record<string, string> = {
  caseHeader: 'Active operations',
  caseSubtitle: 'Triage incoming incidents, assign units, and prevent cascade failures.',
  caseDossier: 'Case dossier',
  status: 'Status',
  mode: 'Mode',
  kind: 'Kind',
  kindCase: 'Case',
  kindRaid: 'Raid',
  teamsRequired: 'Teams required',
  deadline: 'Deadline',
  duration: 'Duration',
  remaining: 'Remaining',
  notStarted: 'Not started',
  stagePrefix: 'Stage',
  success: 'Success',
  noAssignedTeam: 'No assigned team',
  assigned: 'Assigned',
  assignedTeams: 'Assigned teams',
  requiredRoles: 'Required role coverage',
  requiredTags: 'Required tags',
  preferredTags: 'Preferred tags',
  operationalTags: 'Operational tags',
  availableTeamOdds: 'Available team odds',
  raidAtCapacityHint: 'Raid at capacity for new assignments.',
  eligibleTeamsHint: 'Eligible teams are ranked by success odds.',
  noEligibleResponseUnits: 'No eligible response units available.',
  resolvedNoNewAssignments: 'Resolved cases do not accept new assignments.',
  noArchivedLoreStub: 'No archived lore stub available.',
  assignedTo: 'Assigned to',
  unassigned: 'Unassigned',
  assignUpToN: 'Assign up to {n} team{s}',
  assignOneTeam: 'Assign one team',
  oddsSuccessAbbr: 'S',
  oddsPartialAbbr: 'P',
  oddsFailAbbr: 'F',
  removeTeam: 'Remove',
  tags: 'Tags',
  caseWeeklyReports: 'Weekly reports',
  caseWeeklyReportsHint: 'After-action reports that reference this case or its weekly notes.',
  caseWeeklyReportLink: 'Week {week} report',
  loreStub: 'Intelligence stub',
}

/**
 * Mission triage list covert-prep chip labels (SPE-2255).
 */
export const MISSION_TRIAGE_COVERT_PREP_LABELS = {
  concealmentRequested: 'Covert requested',
  concealmentPreview: 'Covert next week',
  coverStrain: 'Cover strain',
  leaveBehindStaged: 'Leave-behind staged',
  forensicStrain: 'Forensic strain',
  deferralNote:
    'Deferring may let infiltration exposure escalate before you can prep covert follow-up on case detail.',
} as const

/** Mission triage disposition actions (SPE-16 slice 5). */
export const MISSION_TRIAGE_DISPOSITION_LABELS = {
  routeNow: 'Route now',
  defer: 'Defer',
  ignore: 'Ignore',
  clear: 'Clear disposition',
  routeDetail: 'Mark for operational planning this week. Assign a response unit when ready.',
  deferDetail: 'Accept delay; escalation may continue while deferred.',
  ignoreDetail: 'Deprioritize in the triage list this week. Does not dismiss the case.',
  activeRoute: 'Routed for planning',
  activeDefer: 'Deferred',
  activeIgnore: 'Ignored this week',
  assignDistinct:
    'Team assignment deploys the mission. Triage disposition only records weekly planning intent.',
} as const

/** Mission triage deferral comparison columns (SPE-16 slice 2). */
export const MISSION_TRIAGE_DEFERRAL_COMPARE_LABELS = {
  covertPrepCost: 'Covert prep load',
  deferralRisk: 'If deferred',
  escalationCarryover: 'Carryover',
  covertPrepConcealmentDetail: 'Concealment or posture prep on case detail before advance week.',
  covertPrepLeaveBehindDetail: 'Leave-behind staged; forensic fallout may compound next resolve.',
  covertPrepForensicDetail:
    'Forensic budget strained; investigation questions cost more before resolve.',
  carryoverLinkLabel: 'Escalation carryover',
  carryoverLinkDetail:
    'Deferred work can worsen under escalation thresholds and incident pressure curves next week.',
} as const

const DEFERRAL_COMPARE_TONE_VALUES = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
} as const

export function formatMissionTriageCovertPrepCostValue(
  tone: keyof typeof DEFERRAL_COMPARE_TONE_VALUES
): string {
  return DEFERRAL_COMPARE_TONE_VALUES[tone]
}

export function formatMissionTriageCovertPrepCostDetail(
  effectiveActionLabel: string,
  awarenessPercent: number,
  hasCoverStrain: boolean
): string {
  const strain = hasCoverStrain ? ' · cover strain' : ''
  return `${effectiveActionLabel} · awareness ${awarenessPercent}%${strain}`
}

export function formatMissionTriageDeferralRiskValue(
  tone: keyof typeof DEFERRAL_COMPARE_TONE_VALUES,
  escalationRisk: number
): string {
  return `${DEFERRAL_COMPARE_TONE_VALUES[tone]} (${escalationRisk}/20)`
}

export function formatMissionTriageDeferralRiskDetail(
  deadlineRemaining: number,
  stage: number
): string {
  const weeksLeft = Math.max(0, Math.trunc(deadlineRemaining))

  if (weeksLeft <= 0) {
    return `Deadline due this week · stage ${stage}`
  }

  const deadlineWord = weeksLeft === 1 ? 'week' : 'weeks'
  return `Deadline ${weeksLeft} ${deadlineWord} left · stage ${stage}`
}

export function formatMissionTriageDeferralCarryoverLink(
  tone: keyof typeof DEFERRAL_COMPARE_TONE_VALUES
): string {
  return DEFERRAL_COMPARE_TONE_VALUES[tone]
}

export function formatMissionTriageDeferralCarryoverDetail(stage: number, kind: string): string {
  const kindLabel = kind === 'raid' ? 'raid incident' : 'case'
  return `Stage ${stage} ${kindLabel} · unresolved work may carry into next week`
}

export function formatMissionTriageInfiltrationTracksLabel(
  probeProgressPercent: number,
  awarenessPercent: number
): string {
  return `Probe ${probeProgressPercent}% · awareness ${awarenessPercent}%`
}

export function formatMissionTriageInfiltrationTracksTitle(
  stageLabel: string,
  plannedActionLabel: string
): string {
  return `${stageLabel} · planned ${plannedActionLabel}`
}

export function formatMissionTriageForensicCustodyTitle(
  markerCount: number,
  remainingQuestions: number
): string {
  const markerWord = markerCount === 1 ? 'marker' : 'markers'
  const questionWord = remainingQuestions === 1 ? 'question' : 'questions'
  return `${markerCount} custody ${markerWord}; ${remainingQuestions} forensic ${questionWord} left`
}

export function formatMissionTriageForensicBudgetExhaustedTitle(
  spent: number,
  granted: number
): string {
  return `Forensic budget exhausted (${spent}/${granted})`
}

/**
 * Agency-themed labels used across operational views.
 */
export const AGENCY_LABELS: Record<string, string> = {
  commandName: 'Directorate Command',
  responseUnit: 'Response Unit',
  fieldAgent: 'Field Agent',
  operationsLedger: 'Operations Ledger',
}

/**
 * Teams page copy.
 */
export const TEAM_UI_LABELS: Record<string, string> = {
  teamHeader: 'Task-force roster',
  teamSubtitle: 'Monitor assignments, fatigue, and specialist coverage across units.',
  agents: 'Agents',
  coreCoverage: 'Core coverage',
  currentAssignment: 'Current assignment',
  capabilitySummary: 'Capability summary',
  derivedFromRosterOnly: 'Derived from the current roster only',
  noActiveAgentsAssigned: 'No active agents assigned to this unit.',
  noTagCoverage: 'No tag coverage',
  avgFatigue: 'Avg fatigue',
  role: 'Role',
  fatigue: 'Fatigue',
}

/**
 * Team fatigue guidance and empty state messages.
 */
export const TEAM_GUIDANCE: Record<string, string> = {
  fatigueTitle: 'Team Fatigue Guide',
  steadyBand: 'Steady',
  steadyDescription: 'Team is rested and operates at full capacity.',
  stressedBand: 'Stressed',
  stressedDescription:
    'Team fatigue is building. Success odds begin to decline; consider reassignment.',
  overstretchedBand: 'Overstretched',
  overstretchedDescription:
    'Team is critically fatigued. Major penalty to success rates. Prioritize rest or replacement.',
  noTeamsFilteredSubtitle:
    'Adjust filters to find teams. All teams may be: assigned to active operations, filtered by fatigue level, or sorted by preference.',
  unassignedTeams:
    'Unassigned teams can be deployed to new operations. Hover cards to see suggested cases.',
  assignedTeamsStatus: 'Assigned teams show progress toward case completion and remaining weeks.',
  fatigueImpactHint:
    'Higher fatigue reduces success odds on new assignments. Monitor fatigue before deployment.',
}

export const CARD_UI_TEXT: Record<string, string> = {
  pageHeading: 'Party Cards',
  pageSubtitle: 'Draw, stage, and monitor tactical modifier cards before weekly resolution.',
  handHeading: 'Current hand',
  deckHeading: 'Deck',
  discardHeading: 'Discard',
  queuedHeading: 'Queued plays',
  drawCard: 'Draw card',
  discardCard: 'Discard',
  noHand: 'No cards in hand.',
  noQueued: 'No cards queued for resolution.',
  targetCase: 'Target case',
  targetTeam: 'Target team',
}

/**
 * Cases page instructional text and empty states.
 */
export const CASES_GUIDANCE: Record<string, string> = {
  noOpenCases: 'No open cases at this time. The threat level is low.',
  noActiveCases: 'No active deployments in progress. Visit cases to begin an operation.',
  noResolvedCases: 'No resolved cases yet. Complete operations to build the archive.',
  modeExplanation:
    'Mode determines how success is calculated. Threshold is deterministic; Probability uses odds; Deterministic requires tag match.',
  stageWarning:
    'Stage 4+ cases auto-escalate if deadlines lapse. Prioritize high-stage operations.',
  allCasesFiltered:
    'No cases match the current filters. Try clearing filters or visiting the intel browser to review templates.',
  tagBlockHint:
    'Some cases require specific team tags or baseline role coverage to be eligible for assignment. Only matching teams appear in the odds list.',
}

/**
 * Agents page and roster guidance.
 */
export const AGENTS_GUIDANCE: Record<string, string> = {
  pageHeading: 'Agents',
  pageSubtitle:
    'Operational roster surface for current field readiness, assignments, fatigue, and training posture.',
  openRegistryLabel: 'Open registry',
  metricTotalRoster: 'Total roster',
  metricDeployed: 'Deployed',
  metricTraining: 'Training',
  metricUnavailable: 'Unavailable',
  statusGuideHeading: 'Agent Status Guide',
  currentRosterHeading: 'Current roster',
  rosterSubtitle:
    'Filter by role, status, team, fatigue, and training state without mutating the roster.',
  filterRoleLabel: 'Role',
  filterStatusLabel: 'Status',
  filterTeamLabel: 'Team',
  filterFatigueLabel: 'Fatigue',
  filterTrainingStateLabel: 'Training state',
  allRolesLabel: 'All roles',
  allStatusesLabel: 'All statuses',
  activeLabel: 'Active',
  injuredLabel: 'Injured',
  recoveringLabel: 'Recovering',
  deadLabel: 'Dead',
  allTeamsLabel: 'All teams',
  reservePoolLabel: 'Reserve pool',
  responseUnitPrefix: 'Response Unit',
  allBandsLabel: 'All bands',
  steadyLabel: 'Steady',
  strainedLabel: 'Strained',
  criticalLabel: 'Critical',
  allTrainingStatesLabel: 'All',
  notTrainingLabel: 'Not training',
  operativeRosterLabel: 'Operative roster',
  noAgentsMatch: 'No agents match the current filters.',
  assignmentLabel: 'Assignment',
  teamLabel: 'Team',
  scoreLabel: 'Score',
  fatigueLabel: 'Fatigue',
  trainingLabel: 'Training',
  rosterReadOnly:
    'Agent roster reflects live operational state. Use recruitment to expand it and training to shape readiness.',
  deployedStatus:
    'Deployed agents are unavailable for new operations until their assignment completes.',
  trainingStatus: 'Training agents are unavailable for field duty until their program finishes.',
  unavailableStatus:
    'Unavailable agents cannot be assigned to teams or operations until they are reactivated.',
  tagExplanation:
    'Agent tags determine which operations they are eligible for. Mixed-tag teams increase flexibility but lower specialization.',
  fatigueExplanation:
    'Fatigue is carried at the team level and impacts success rates. Rested teams perform better.',
}

/**
 * Recruitment page guidance.
 */
export const RECRUITMENT_GUIDANCE: Record<string, string> = {
  noCandidates:
    'No active candidates in the pipeline. Candidates expire after their deadline has passed.',
  candidateExpiring:
    'This candidate expires soon. Press recruitment to proceed or their slot will close automatically.',
  candidateHiddenOverall:
    'Overall fit is still obscured. Rely on visible rumor tags, role, and outlook until more intel arrives.',
  impressionExplained:
    "Impression is the candidate's first perception of the agency—can change with successful ops or exposure.",
  outlookExplained:
    'Outlook reflects likelihood they will join the agency or accept a team role long-term.',
  teamworkExplained:
    'Teamwork score suggests compatibility with multi-agent operations and team dynamics.',
}

/**
 * Training division page copy.
 */
export const TRAINING_UI_TEXT: Record<string, string> = {
  pageTitle: 'Training Division',
  pageSubtitle:
    'Training advances on weekly ticks. Ready agents can be queued immediately, deployed agents are blocked, and active trainees return with improved capability.',
  openSquadBuilder: 'Open squad builder',
  backToOperationsDesk: 'Back to Operations Desk',
  totalAgents: 'Total agents',
  readyNow: 'Ready now',
  inTraining: 'In training',
  deployed: 'Deployed',
  queueDepth: 'Queue depth',
  catalogHeading: 'Training catalog',
  activeQueueHeading: 'Active queue',
  noActiveQueue: 'No training programs are active.',
  eligibleRosterHeading: 'Eligible roster',
  eligibleRosterHint: 'Ready agents can be queued from here',
  recentEventsHeading: 'Recent training events',
  noRecentEvents: 'No training events recorded yet.',
  completionsHeading: 'Recent completions timeline',
  noRecentCompletions: 'No completed programs recorded yet.',
}

/**
 * Reports page copy.
 */
export const REPORT_UI_TEXT: Record<string, string> = {
  pageHeading: 'Reports',
  pageSubtitle: 'Weekly after-action summaries from Directorate operations.',
  notesHeader: 'Field notes',
  noteCategoryLabel: 'Note category',
  allNoteCategories: 'All note categories',
  snapshotsHeader: 'Historical snapshots',
  newCasesHeader: 'New cases',
  progressedCasesHeader: 'Progressed cases',
  partialCasesHeader: 'Partial cases',
  noNotesWeek: 'No notes were recorded for this week.',
  spawnedCasesHeader: 'Spawned cases',
  resolvedCasesHeader: 'Resolved cases',
  failedCasesHeader: 'Failed cases',
  unresolvedCasesHeader: 'Unresolved cases',
  teamStatusHeader: 'Team status',
  noNewCases: 'No new cases were recorded.',
  noProgressedCases: 'No progressed cases were recorded.',
  noPartialCases: 'No partial cases were recorded.',
  noSpawnedCases: 'No spawned cases were recorded.',
  noResolvedCases: 'No resolved cases were recorded.',
  noFailedCases: 'No failed cases were recorded.',
  noUnresolvedCases: 'No unresolved cases were recorded.',
  noTeamStatus: 'No team status was recorded for this week.',
  deployedRecoveryLabel: 'Deployed recovery',
  staleSnapshotSuffix: 'archived snapshot',
  previousWeekLink: 'Previous week',
  nextWeekLink: 'Next week',
}

export const INTEL_UI_TEXT: Record<string, string> = {
  pageHeading: 'Threat Intel',
  pageSubtitle:
    'Review template families, escalation paths, raid posture, and starter-team fit before pressure compounds.',
  searchLabel: 'Search',
  searchPlaceholder: 'Search templates, tags, or escalation paths',
  modeLabel: 'Mode',
  kindLabel: 'Kind',
  pressureLabel: 'Pressure',
  requiredTagLabel: 'Required tag',
  raidCapableLabel: 'Raid-capable only',
  allModes: 'All modes',
  allKinds: 'All kinds',
  allPressure: 'All pressure',
  allRequiredTags: 'All required tags',
  noMatches: 'No templates match the current intel filters.',
  showingResults: 'Showing {count} of {total} templates',
  templateId: 'Template ID',
  family: 'Family',
  threatRating: 'Threat rating',
  likelyPressure: 'Likely escalation',
  overview: 'Template overview',
  loreStub: 'Archive stub',
  noLoreStub: 'No archived intel is available for this template yet.',
  escalationOnFail: 'On fail',
  escalationOnUnresolved: 'On unresolved',
  incomingSignals: 'Spawned by',
  noEscalationTargets: 'No follow-up templates are declared.',
  noIncomingSignals: 'No other templates currently point here.',
  stageDelta: 'Stage delta',
  spawnCount: 'Spawn count',
  convertsAt: 'Converts to raid at stage {stage}',
  directRaidTemplate: 'Direct raid template',
  starterCoverage: 'Starter-team fit',
  starterCoverageHint:
    'Calculated against the opening roster with no current assignments and no historical fatigue carryover.',
  starterCoverageReady: 'Starter-ready',
  starterCoverageBlocked: 'Required-tag blocked',
  dominantStats: 'Dominant stats',
}

export const SELF_CENSORING_INFORMATION_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Self-censoring information registry',
  pageSubtitle:
    'Read-only operations view over persisted cognitive-hazard intake records and contradiction projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  retentionActiveLabel: 'Retention timers active',
  rediscoveryActiveLabel: 'Rediscovery loops active',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Negative facts and rediscovery loops mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No self-censoring information records',
  emptyBody:
    'Persisted self-censoring information records will appear here after hydration. This mirror does not re-validate hidden truth.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Contradiction signals come from dossier projection; negative facts display unverified absence predicates as stored.',
  labelColumn: 'Label',
  resistanceColumn: 'Propagation resistance',
  negativeFactsColumn: 'Negative facts',
  retentionColumn: 'Retention timer',
  rediscoveryColumn: 'Rediscovery loop',
  failureModeColumn: 'Failure / archive',
  contradictionColumn: 'Contradiction signals',
  confidenceColumn: 'Confidence',
  parentCasePrefix: 'Parent case:',
  lastAlarmPrefix: 'Last alarm:',
  warningRefSuffix: 'forgotten warning ref(s)',
  redactedSuffix: 'Partial redaction',
}

export const COVER_STORY_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Cover-story lifecycle registry',
  pageSubtitle:
    'Read-only operations view over persisted cover-story records and weekly lifecycle projection snapshots.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  coverStressActiveLabel: 'Cover stress active',
  coverCollapsedLabel: 'Cover collapsed',
  repairInProgressLabel: 'Repair in progress',
  weekLabel: 'Simulation week',
  readOnlyNote:
    'Lifecycle projections mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No cover-story records',
  emptyBody:
    'Persisted cover-story records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Contradiction channel hints show aggregate pressure only; weekly snapshot column displays persisted lifecycle projection when available.',
  labelColumn: 'Label',
  lifecycleColumn: 'Lifecycle',
  contradictionColumn: 'Contradiction signals',
  opsFlagsColumn: 'Ops flags',
  weeklySnapshotColumn: 'Weekly snapshot',
  contradictionPressureLabel: 'Contradiction pressure',
  coverCapacityScoreLabel: 'Cover capacity score',
  channelCountPrefix: 'Active channels:',
  motivationPrefix: 'Motivation:',
  exposurePrefix: 'Exposure:',
  confidenceColumn: 'Confidence',
  latestRepairPrefix: 'Latest repair:',
  unknownFieldsPrefix: 'Unknown fields:',
  snapshotWeekPrefix: 'Snapshot week',
  redactedSuffix: 'Partial redaction',
}

export const TRUTH_LAYER_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Truth-layer record registry',
  pageSubtitle:
    'Read-only operations view over persisted claim, doctrine, and verification layers plus weekly ops projection snapshots.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  layerDivergenceLabel: 'Layer divergence',
  mythInfrastructureActiveLabel: 'Myth infrastructure active',
  correctionPressureLabel: 'Correction pressure',
  weekLabel: 'Simulation week',
  readOnlyNote:
    'Claim, doctrine, and verification slots mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No truth-layer records',
  emptyBody:
    'Persisted truth-layer records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Review slots stay separate; weekly snapshot column displays persisted ops projection when available.',
  labelColumn: 'Label',
  claimColumn: 'Claim layer',
  doctrineColumn: 'Doctrine layer',
  verificationColumn: 'Verification layer',
  opsFlagsColumn: 'Ops flags',
  weeklySnapshotColumn: 'Weekly snapshot',
  claimSlotLabel: 'Claim',
  doctrineSlotLabel: 'Doctrine',
  verificationSlotLabel: 'Verification',
  confidenceColumn: 'Confidence',
  confidencePrefix: 'Source:',
  tierPrefix: 'Tier:',
  layerDivergencePrefix: 'Layer divergence:',
  competingLayerSuffix: 'competing layer ref(s)',
  unknownFieldsPrefix: 'Unknown fields:',
  snapshotWeekPrefix: 'Snapshot week',
  mythDrivesOpsPrefix: 'Myth drives ops without verification:',
  redactedSuffix: 'Partial redaction',
}

export const PUBLIC_DISCLOSURE_CAMPAIGN_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Public affairs briefing',
  pageHeading: 'Disclosure campaign posture',
  pageSubtitle:
    'Institutional readout of post-secrecy disclosure progression and regional public-trust bands.',
  backToDeskLabel: 'Back to Operations Desk',
  activeDisclosureLabel: 'Active disclosures',
  dominantAwarenessLabel: 'Dominant awareness band',
  cooperationBandLabel: 'Public cooperation band',
  segmentDivergenceLabel: 'Audience segment trust',
  segmentTrustChipsHeading: 'Population and channel trust segments',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Awareness and regional trust reflect the latest weekly progression. Posture choices adjust projected cooperation bands without revealing raw trust scores.',
  emptyTitle: 'No active disclosure campaigns',
  emptyBody:
    'When disclosure records enter play, campaign posture and regional trust bands will appear here.',
  campaignsHeading: 'Active campaigns',
  campaignsSubtitle:
    'Each card summarizes public-awareness posture without operational or verification-layer detail.',
  awarenessPrefix: 'Awareness:',
  falloutPrefix: 'Fallout:',
  objectivePrefix: 'Objective:',
  regionalTrustHeading: 'Regional public trust',
  coverNarrativePrefix: 'Linked cover narrative:',
  confidencePrefix: 'Assessment:',
  redactedSuffix: 'Partial redaction',
  postureChoiceHeading: 'Disclosure posture choice',
  postureChoiceSubtitle:
    'Set institutional messaging posture for this campaign. Effects appear in cooperation bands and weekly trust outcomes.',
  postureChoiceSelectedPrefix: 'Selected posture:',
  postureChoiceUnselectedLabel: 'No posture selected',
  postureChoiceEffectNote:
    'Cooperation and segment-trust summaries above reflect your selected posture without exposing redacted trust scores.',
}

export const PUBLIC_DISCLOSURE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Public disclosure state registry',
  pageSubtitle:
    'Read-only operations view over persisted post-secrecy campaign records and regional trust projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  disclosureActiveLabel: 'Disclosure active',
  normalizationInputLabel: 'Normalization inputs',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Awareness, fallout, and regional trust mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No public disclosure records',
  emptyBody:
    'Persisted public disclosure records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Regional trust comes from disclosure regional projection; transition history displays scheduled awareness steps as stored.',
  labelColumn: 'Label',
  awarenessColumn: 'Awareness',
  falloutColumn: 'Fallout phase',
  regionalTrustColumn: 'Regional trust',
  oversightColumn: 'Oversight pressure',
  transitionColumn: 'Transition history',
  normalizationColumn: 'Normalization / contracts',
  confidenceColumn: 'Confidence',
  campaignPivotPrefix: 'Campaign pivot:',
  coverCapacityFailureSuffix: 'Cover capacity failure declared',
  linkedContractSuffix: 'linked contract hook(s)',
  redactedSuffix: 'Partial redaction',
}

export const RECURRENT_CATASTROPHE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Recurrent catastrophe amelioration registry',
  pageSubtitle:
    'Read-only operations view over persisted recurrence-cycle records and next-recurrence risk projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  impossiblePreventionLabel: 'Impossible prevention ceiling',
  criticalSeverityLabel: 'Critical severity band',
  linkedReviewsLabel: 'Linked reviews',
  unresolvedReviewRefsLabel: 'Unresolved review refs',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Cadence, amelioration posture, and severity bands mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No recurrent catastrophe amelioration records',
  emptyBody:
    'Persisted recurrent catastrophe records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Severity bands and risk scores come from next-recurrence risk projection at the current simulation week.',
  labelColumn: 'Label',
  cadenceColumn: 'Cadence / amelioration',
  preventionColumn: 'Prevention ceiling',
  recurrenceColumn: 'Recurrence history',
  riskColumn: 'Risk projection',
  reviewLinksColumn: 'Linked review summaries',
  confidenceColumn: 'Confidence',
  failureModePrefix: 'Failure mode:',
  ameliorationPrefix: 'Active amelioration:',
  preventionTacticPrefix: 'Active prevention:',
  lastOccurrencePrefix: 'Last occurrence:',
  damageLedgerPrefix: 'Damage ledger:',
  reviewRefPrefix: 'Post-incident review:',
  unresolvedReviewRefPrefix: 'Unresolved review ref:',
  riskScorePrefix: 'Risk score:',
  activeAmeliorationCountPrefix: 'Active amelioration count:',
  validationWarningPrefix: 'Validation warning(s):',
  redactedSuffix: 'Partial redaction',
}

export const POST_INCIDENT_REVIEW_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Post-incident review registry',
  pageSubtitle:
    'Read-only operations view over persisted retrospective records and review summary projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  externalAuditRouteLabel: 'External audit route',
  recurrenceObservedLabel: 'Recurrence observed',
  qualifyingCaseCloseoutLabel: 'Qualifying case closeouts',
  qualifyingNearCatastropheLabel: 'Near-catastrophe reviews',
  orchestrationCreatedLabel: 'Orchestration-created',
  stubFixtureLabel: 'Stub fixtures',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Review routes, closure outcomes, and milestone spans mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No post-incident review records',
  emptyBody:
    'Persisted post-incident review records will appear here after hydration. This mirror does not re-validate dropped entries.',
  qualifyingRecordsHeading: 'Qualifying incident reviews',
  qualifyingRecordsSubtitle:
    'Orchestration-created case closeout and near-catastrophe threshold retrospectives from weekly advance.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Milestone spans, adherence scores, and recurrence flags come from review summary projection.',
  labelColumn: 'Label',
  sourceColumn: 'Source',
  caseIdColumn: 'Linked case',
  orchestrationWeekColumn: 'Orchestration week',
  routeColumn: 'Review route',
  closureColumn: 'Closure outcome',
  milestoneColumn: 'Milestone timings',
  adherenceColumn: 'Procedure adherence',
  recurrenceColumn: 'Recurrence observed',
  confidenceColumn: 'Confidence',
  milestoneSpanPrefix: 'Span (weeks):',
  discoveryPrefix: 'Discovery:',
  responsePrefix: 'Response:',
  containmentPrefix: 'Containment:',
  recoveryPrefix: 'Recovery:',
  reportingPrefix: 'Reporting:',
  unknownFieldsPrefix: 'Unknown fields:',
  redactedSuffix: 'Partial redaction',
}

export const POST_INCIDENT_REVIEW_RECOMMENDATION_ACTION_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Post-incident recommendation action registry',
  pageSubtitle:
    'Read-only operations view over persisted follow-on action stubs linked to recommendation and qualifying review records.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  linkedRecommendationLabel: 'Linked recommendations',
  linkedQualifyingReviewLabel: 'Linked qualifying reviews',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Action ids, recommendation refs, review refs, and stub suffixes mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No post-incident recommendation action records',
  emptyBody:
    'Persisted action records will appear here after hydration. This mirror does not re-validate dropped entries.',
  linkedRecordsHeading: 'Linked qualifying incident reviews',
  linkedRecordsSubtitle:
    'Actions whose reviewRef matches orchestration-created qualifying case or near-catastrophe reviews.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Follow-on action-stub tokens materialized from recommendation registry entries during weekly advance.',
  labelColumn: 'Label',
  recommendationRefColumn: 'Recommendation ref',
  reviewRefColumn: 'Review ref',
  linkedReviewColumn: 'Linked review',
  stubSuffixColumn: 'Stub suffix',
  orchestrationWeekColumn: 'Orchestration week',
  actionTokenColumn: 'Action token',
  openReviewMirrorLabel: 'Open review mirror',
  openRecommendationMirrorLabel: 'Open recommendation mirror',
  linkedRecommendationPrefix: 'Linked recommendation:',
  linkedReviewPrefix: 'Linked review:',
  caseIdPrefix: 'Case:',
}

export const POST_INCIDENT_REVIEW_RECOMMENDATION_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Post-incident recommendation registry',
  pageSubtitle:
    'Read-only operations view over persisted follow-on recommendation stubs from orchestration-created reviews.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  linkedQualifyingReviewLabel: 'Linked qualifying reviews',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Recommendation ids, review refs, and stub suffixes mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No post-incident recommendation records',
  emptyBody:
    'Persisted recommendation records will appear here after hydration. This mirror does not re-validate dropped entries.',
  linkedRecordsHeading: 'Linked qualifying incident reviews',
  linkedRecordsSubtitle:
    'Recommendations whose reviewRef matches orchestration-created qualifying case or near-catastrophe reviews.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Follow-on stub tokens materialized from review unknownFields during weekly advance.',
  labelColumn: 'Label',
  reviewRefColumn: 'Review ref',
  linkedReviewColumn: 'Linked review',
  stubSuffixColumn: 'Stub suffix',
  orchestrationWeekColumn: 'Orchestration week',
  followOnTokenColumn: 'Follow-on token',
  openReviewMirrorLabel: 'Open review mirror',
  linkedReviewPrefix: 'Linked review:',
  caseIdPrefix: 'Case:',
}

export const RULE_DOCUMENT_COMPLIANCE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Rule document compliance registry',
  pageSubtitle:
    'Read-only operations view over persisted written-conduct binding records and compliance decay projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  breachCountLabel: 'Breach state',
  criticalBandLabel: 'Critical decay band',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Binding posture, decay bands, and audit symptoms mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No rule document compliance records',
  emptyBody:
    'Persisted rule document compliance records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Decay bands and audit symptoms come from compliance decay projection at the current simulation week.',
  labelColumn: 'Label',
  bindingColumn: 'Binding',
  complianceColumn: 'Compliance',
  decayColumn: 'Decay band',
  auditColumn: 'Audit symptoms',
  confidenceColumn: 'Confidence',
  documentRefPrefix: 'Document:',
  physicalCopyPrefix: 'Physical copy:',
  auditorPrefix: 'Auditors:',
  breachConsequencePrefix: 'Breach consequence:',
  driftProbabilityPrefix: 'Drift/week:',
  validationWarningPrefix: 'Validation warning(s):',
  redactedSuffix: 'Partial redaction',
}

export const MASS_ANOMALOUS_POPULATION_EMERGENCE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Mass anomalous population emergence registry',
  pageSubtitle:
    'Read-only operations view over persisted population emergence records and governance-surge projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  registrationBacklogActiveLabel: 'Registration backlog active',
  collapsedMasqueradeLabel: 'Collapsed masquerade',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Magnitude, backlog, triage lanes, and governance surge mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No mass anomalous population emergence records',
  emptyBody:
    'Persisted population emergence records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Governance surge band comes from week-drift projection; education burden may elevate under collapsed masquerade.',
  labelColumn: 'Label',
  magnitudeColumn: 'Magnitude',
  backlogColumn: 'Registration backlog',
  governanceColumn: 'Governance / surge refs',
  triageColumn: 'Triage / rights review',
  educationColumn: 'Education burden',
  surgeColumn: 'Governance surge',
  confidenceColumn: 'Confidence',
  populationEstimatePrefix: 'Population estimate:',
  backlogWeeksSuffix: 'weeks remaining',
  rightsReviewPrefix: 'Rights review:',
  effectiveEducationPrefix: 'Effective:',
  redactedSuffix: 'Partial redaction',
}

export const CONTAINED_PERSON_INTEGRATED_HEALTH_BUNDLE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Contained person integrated health bundles',
  pageSubtitle:
    'Read-only operations view over persisted integrated health bundles, therapeutic care schedule links, medication/custody/welfare-debt field links, and mental-state markers.',
  backToDeskLabel: 'Back to Operations Desk',
  totalBundlesLabel: 'Persisted bundles',
  criticalMentalStateLabel: 'Critical mental state',
  distressedMentalStateLabel: 'Distressed mental state',
  coercedMedicationLabel: 'Coerced medication links',
  rightsReviewPendingLabel: 'Rights review pending',
  unresolvedWelfareDebtLabel: 'Unresolved welfare debt',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Mental-state bands, humane-care risk, and wired link groups mirror hydrated GameState only. Invalid bundles dropped on hydrate are not shown here.',
  emptyTitle: 'No contained person integrated health bundles',
  emptyBody:
    'Persisted integrated health bundles will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted bundles',
  recordsSubtitle:
    'Therapeutic care, medication, custody, and welfare-debt links reflect persisted bundle fields; they are read-time routing aids, not objective truth.',
  labelColumn: 'Label',
  mentalStateColumn: 'Mental state',
  humaneCareColumn: 'Humane care',
  scheduleLinksColumn: 'Therapeutic care links',
  medicationLinksColumn: 'Medication links',
  custodyLinksColumn: 'Custody links',
  welfareDebtLinksColumn: 'Welfare debt links',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  humaneCareRiskPrefix: 'Risk score:',
  complianceRiskPrefix: 'Compliance risk:',
  interactionRiskPrefix: 'Interaction risk:',
  lockdownEscalationSuffix: 'Lockdown escalation likely',
  adverseReactionSuffix: 'Adverse reaction flagged',
  rightsReviewPendingSuffix: 'Rights review pending',
  containmentBenefitPrefix: 'Containment benefit:',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const NAMING_HAZARD_DESCRIPTOR_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Naming-hazard descriptor registry',
  pageSubtitle:
    'Read-only operations view over persisted naming-hazard descriptor records, safe-label projections, and intake cross-links.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  redactedSubstitutionLabel: 'Redacted substitution',
  crossLinkedLabel: 'Cross-linked records',
  orchestratedLabel: 'Orchestrated records',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Substitution policy, confidence erosion, and cross-link labels mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No naming-hazard descriptor records',
  emptyBody:
    'Persisted naming-hazard descriptor records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Safe briefing and map labels use projectSafeLabel at read time; they are not objective truth.',
  labelColumn: 'Descriptor',
  substitutionColumn: 'Substitution state',
  crossLinkColumn: 'Intake cross-links',
  orchestrationColumn: 'Weekly orchestration',
  confidenceColumn: 'Confidence',
  poolPrefix: 'Pool:',
  mapModePrefix: 'Map mode:',
  briefingLabelPrefix: 'Briefing:',
  mapLabelPrefix: 'Map:',
  intakeTopicPrefix: 'Topic:',
  redactedFieldsPrefix: 'Redacted fields:',
  redactedSuffix: 'Substitution redacted',
  confidenceRedactedSuffix: 'Confidence redacted',
  validationWarningPrefix: 'Validation warnings:',
}

export const COERCIVE_CONTAINED_PERSON_PROTOCOL_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Coercive contained-person protocol registry',
  pageSubtitle:
    'Read-only operations view over persisted coercive protocol records and read-time containment-care tradeoff plus coercion-risk review projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  stableContainmentLabel: 'Stable containment dominates',
  abusivePostureLabel: 'Abusive posture',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Handling modes, tradeoff scores, and coercion-risk flags mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No coercive contained person protocol records',
  emptyBody:
    'Persisted coercive protocol records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Tradeoff and risk-review projections are read-time only, not objective truth. Owner refs display as stored.',
  labelColumn: 'Label',
  handlingColumn: 'Handling posture',
  tradeoffColumn: 'Containment vs care',
  riskReviewColumn: 'Coercion risk review',
  ownerRefsColumn: 'Owner refs',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  subjectFitPrefix: 'Subject fit:',
  consentPrefix: 'Consent confidence:',
  stabilityGainPrefix: 'Stability gain:',
  harmRiskPrefix: 'Harm risks:',
  stableContainmentSuffix: 'Stable containment dominates care',
  coercionRiskPrefix: 'Coercion risk:',
  contradictionCheckPrefix: 'Contradiction checks:',
  contradictionCheckUnknownFieldsPrefix: 'Unknown fields:',
  crossSystemTensionPrefix: 'Cross-system tension:',
  integratedHealthLinkedSubjectsLabel: 'Integrated health links',
  crossSystemTensionSubjectsLabel: 'Cross-system tension subjects',
  weeklySnapshotCountLabel: 'Weekly snapshots',
  welfareDebtLinkedRecordsLabel: 'Welfare-debt links',
  factionEthicsLinkedRecordsLabel: 'Faction ethics links',
  accountabilityMatrixLinkedRecordsLabel: 'Accountability matrix links',
  welfareDebtCrossLinkPrefix: 'Welfare-debt cross-links:',
  factionEthicsCrossLinkPrefix: 'Faction ethics cross-links:',
  accountabilityMatrixCrossLinkPrefix: 'Accountability matrix cross-links:',
  factionEthicsProjectionPrefix: 'Permissibility verdict:',
  accountabilityMatrixProjectionPrefix: 'Accountability outcomes:',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const PSYCHOLOGICAL_RESILIENCE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Psychological resilience registry',
  pageSubtitle:
    'Read-only operations view over persisted operator resilience records and read-time depletion, exposure, and treatment-gating projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  exposureElevatedLabel: 'Exposure elevated',
  treatmentGatedLabel: 'Treatment gated',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Depletion bands, exposure scores, and treatment gates mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No psychological resilience records',
  emptyBody:
    'Persisted operator resilience records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Exposure, depletion, and treatment-gating projections are read-time only, not objective truth.',
  labelColumn: 'Label',
  depletionColumn: 'Depletion posture',
  exposureColumn: 'Exposure',
  recoveryColumn: 'Recovery channel',
  projectionColumn: 'Projection signals',
  confidenceColumn: 'Confidence',
  operatorRefPrefix: 'Operator:',
  exposureScorePrefix: 'Exposure score:',
  exposureEventPrefix: 'Exposure events:',
  exposureSourcesPrefix: 'Sources:',
  complicationsPrefix: 'Complications:',
  counselingRefPrefix: 'Counseling ref:',
  exposureElevatedSuffix: 'Exposure elevated',
  treatmentGatedSuffix: 'Treatment gated',
  depletionAdvancedSuffix: 'Depletion advanced',
  dutyReliabilitySuffix: 'Duty reliability degraded',
  restRecoverySuffix: 'Rest recovery eligible',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const COGNITIVE_HAZARD_EXPOSURE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Cognitive hazard exposure registry',
  pageSubtitle:
    'Read-only operations view over persisted unified cognitive hazard exposure records, review-band projections, and simulation trigger summaries.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  elevatedExposureLabel: 'Elevated exposure',
  simulationTriggerSubjectsLabel: 'Simulation trigger subjects',
  countermeasureFailedLabel: 'Countermeasure failed',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Exposure pressures, review bands, and trigger chips mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No cognitive hazard exposure records',
  emptyBody:
    'Persisted cognitive hazard exposure records will appear here after hydration. This mirror does not re-validate hidden truth.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Review projections and simulation trigger labels are read-time only; pre-projection field values are not surfaced.',
  labelColumn: 'Label',
  subjectColumn: 'Subject / channels',
  exposureColumn: 'Exposure pressures',
  memoryColumn: 'Memory / countermeasure',
  reviewColumn: 'Review band / effects',
  triggerColumn: 'Simulation triggers',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  fearPressurePrefix: 'Fear:',
  memeticExposurePrefix: 'Memetic:',
  aggregateExposurePrefix: 'Aggregate:',
  agentDutySuffix: 'Agent duty degraded',
  knowledgeIntegritySuffix: 'Knowledge integrity degraded',
  procedureRestrictionSuffix: 'Procedure restriction active',
  countermeasureFailedSuffix: 'Countermeasure failed',
  countermeasureShieldingSuffix: 'Shielding active',
  memoryImpairmentAdvancedSuffix: 'Memory impairment advanced',
  redactedSuffix: 'Partial redaction',
}

export const SURVEILLANCE_INTERVENTION_TUNING_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Surveillance intervention tuning registry',
  pageSubtitle:
    'Read-only operations view over persisted intervention tuning records and read-time surveillance, contact, and collateral-strain projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  monitoringExceedsContactLabel: 'Monitoring exceeds contact',
  sustainedUnderCollateralStrainLabel: 'Sustained under collateral strain',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Intervention levels, signal scores, and horizon outcomes mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No surveillance intervention tuning records',
  emptyBody:
    'Persisted intervention tuning records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Monitoring/contact separation and collateral-strain projections are read-time only, not objective truth.',
  labelColumn: 'Label',
  interventionColumn: 'Intervention level',
  signalsColumn: 'Signal scores',
  horizonColumn: 'Horizon outcomes',
  projectionColumn: 'Projection signals',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  surveillanceSignalPrefix: 'Surveillance signal:',
  meaningfulContactPrefix: 'Meaningful contact:',
  healthcareLoadPrefix: 'Healthcare load:',
  collateralStrainPrefix: 'Collateral strain:',
  tuningRationalePrefix: 'Tuning rationale:',
  monitoringExceedsContactSuffix: 'Monitoring exceeds contact',
  sustainedUnderCollateralStrainSuffix: 'Sustained under collateral strain',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const CONTAINED_PERSON_THERAPEUTIC_CARE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Contained person therapeutic care registry',
  pageSubtitle:
    'Read-only operations view over persisted therapeutic care schedule records and read-time compliance risk projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  degradedChannelLabel: 'Degraded channels',
  suspendedChannelLabel: 'Suspended channels',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Care cadence, channel posture, and compliance risk mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No contained person therapeutic care records',
  emptyBody:
    'Persisted therapeutic care schedule records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Compliance risk and lockdown escalation projections are read-time only, not objective truth.',
  labelColumn: 'Label',
  scheduleColumn: 'Care schedule',
  channelColumn: 'Channel posture',
  complianceColumn: 'Compliance risk',
  staffColumn: 'Staff assignees',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  containmentDependencySuffix: 'Containment dependency',
  missedStreakPrefix: 'Missed streak:',
  suspensionCausePrefix: 'Suspension cause:',
  complianceRiskPrefix: 'Risk score:',
  lockdownEscalationSuffix: 'Lockdown escalation likely',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const WELFARE_DEBT_ACCOUNTING_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Welfare debt accounting registry',
  pageSubtitle:
    'Read-only operations view over persisted welfare-debt accounting records and read-time containment benefit projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  unresolvedCountLabel: 'Unresolved debt',
  escalatedCountLabel: 'Escalated debt',
  mitigatedCountLabel: 'Mitigated debt',
  crossLinkedCountLabel: 'Cross-linked records',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Severity bands, mitigation states, and containment benefit scores mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No welfare debt accounting records',
  emptyBody:
    'Persisted welfare-debt accounting records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Containment benefit scores come from welfare-debt accounting projection at read time; unresolved and escalated states display as stored.',
  labelColumn: 'Label',
  debtColumn: 'Debt category / severity',
  procedureColumn: 'Source procedure',
  reviewColumn: 'Review / mitigation',
  crossLinkColumn: 'Ledger cross-links',
  confidenceColumn: 'Confidence',
  subjectRefPrefix: 'Subject:',
  containmentBenefitPrefix: 'Containment benefit:',
  reviewOwnerPrefix: 'Review owner:',
  mitigationPathPrefix: 'Mitigation path:',
  factionEthicsProjectionPrefix: 'Permissibility verdict:',
  accountabilityMatrixProjectionPrefix: 'Outcome summary:',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const ENTITY_WELFARE_RECLASSIFICATION_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Entity welfare reclassification registry',
  pageSubtitle:
    'Read-only operations view over persisted entity welfare reclassification records and read-time pressure projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  pendingCountLabel: 'Pending review',
  terminalCountLabel: 'Terminal decisions',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Disposition, review gates, and reclassification pressure mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No entity welfare reclassification records',
  emptyBody:
    'Persisted entity welfare reclassification records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Pressure forecasts come from reclassification projection at read time; pending and terminal states display as stored.',
  labelColumn: 'Label',
  dispositionColumn: 'Disposition / state',
  permissionsColumn: 'Permissions',
  accessOutcomeColumn: 'Access outcome',
  siteClearanceColumn: 'Site clearance',
  dualLoyaltyColumn: 'Dual loyalty',
  protectedStatusColumn: 'Protected status',
  pressureColumn: 'Reclassification pressure',
  reviewColumn: 'Evidence / history',
  confidenceColumn: 'Confidence',
  priorThreatPrefix: 'Prior threat:',
  reviewGatePrefix: 'Review gate:',
  welfareDebtLinkedSuffix: 'Welfare debt linked',
  staffMoralePrefix: 'Staff morale:',
  liabilityPrefix: 'Liability:',
  publicRiskPrefix: 'Public risk:',
  containmentRevisionPrefix: 'Containment revision:',
  validationWarningPrefix: 'Validation warnings:',
  redactedSuffix: 'Partial redaction',
}

export const AFFILIATION_PERSON_STATUS_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Affiliation person-status records',
  pageSubtitle:
    'Read-only operations view over persisted affiliation person-status evidence and composed clearance projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  candidateLinkedLabel: 'Candidate links',
  welfareLinkedLabel: 'Welfare links',
  restrictedOrBlockedLabel: 'Restricted / blocked',
  missingReferenceLabel: 'Missing refs',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Status records mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here, and this mirror does not mutate weekly state.',
  emptyTitle: 'No affiliation person-status records',
  emptyBody:
    'Persisted affiliation person-status records will appear here after hydration. This mirror does not re-validate dropped entries.',
  fileAccessQueueHeading: 'File access work queue',
  fileAccessQueueSubtitle:
    'Read-only queue derived from existing file permission and site/facility clearance decisions.',
  fileAccessQueueTotalLabel: 'Total',
  fileAccessQueueBlockedLabel: 'Blocked',
  fileAccessQueueRestrictedLabel: 'Restricted',
  fileAccessQueueMissingLabel: 'Missing review',
  fileAccessQueueStatusColumn: 'Queue status',
  recommendedActionColumn: 'Recommended action',
  actionStatusColumn: 'Action status',
  recordActionButtonLabel: 'Record action',
  pendingActionStatusLabel: 'Not recorded',
  recordEvidenceResolutionButtonLabel: 'Record evidence resolution',
  pendingEvidenceResolutionStatusLabel: 'Evidence unresolved',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Projection labels compose existing SPE-1046 evaluators at read time; mission routing still uses explicit team and member tags.',
  subjectColumn: 'Subject',
  linksColumn: 'Links',
  onboardingColumn: 'Onboarding',
  permissionsColumn: 'Permissions',
  roomAccessColumn: 'Room access',
  fileAccessColumn: 'File access',
  facilityFileAccessColumn: 'Facility file access',
  housingAccessColumn: 'Housing access',
  siteClearanceColumn: 'Site clearance',
  dualLoyaltyColumn: 'Dual loyalty',
  protectedStatusColumn: 'Protected status',
  revocationColumn: 'Revocation',
  reasonCodesColumn: 'Reason codes',
  candidateRefPrefix: 'Candidate:',
  welfareRefPrefix: 'Welfare:',
}

export const VISUAL_TRIGGER_HAZARD_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Visual trigger hazard registry',
  pageSubtitle:
    'Read-only operations view over persisted visual-trigger hazard records and read-time compliance, exposure, and awareness projections.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  activePursuitLabel: 'Active pursuit',
  disposalCompliancePendingLabel: 'Disposal compliance pending',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Disposal compliance, exposure-chain risk, and awareness escalation mirror hydrated GameState only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No visual trigger hazard records',
  emptyBody:
    'Persisted visual trigger hazard records will appear here after hydration. This mirror does not re-validate dropped entries.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Compliance posture uses current campaign week; exposure and awareness projections are read-time only, not objective truth.',
  labelColumn: 'Label',
  triggerColumn: 'Trigger / derivative',
  pursuitColumn: 'Pursuit posture',
  disposalColumn: 'Disposal compliance',
  exposureColumn: 'Exposure chain',
  awarenessColumn: 'Awareness escalation',
  confidenceColumn: 'Confidence',
  targetPrefix: 'Targets:',
  projectedPursuitPrefix: 'Projected:',
  pursuitPressurePrefix: 'Pressure:',
  pendingMediaPrefix: 'Pending media:',
  broadcastRiskPrefix: 'Broadcast risk:',
  manifestationRiskPrefix: 'Manifestation:',
  dreamIntrusionSuffix: 'Dream intrusion flagged',
  validationWarningPrefix: 'Validation warnings:',
}

export const SPE_947_EVALUATOR_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Hazardous content propagation',
  pageSubtitle:
    'Read-only operations view over persisted SPE-947 platforms, counter-memetic plans, content owners, and post-case media cases.',
  backToDeskLabel: 'Back to Operations Desk',
  platformsLabel: 'Platforms',
  plansLabel: 'Counter-memetic plans',
  ownersLabel: 'Content owners',
  mediaCasesLabel: 'Post-case media cases',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Labels mirror hydrated GameState fields only. This surface does not re-run SPE-947 evaluators or invent parent acceptance evidence.',
  emptyTitle: 'No hazardous content evaluator records',
  emptyBody:
    'Persisted SPE-947 platform, plan, owner, and media-case maps will appear here after hydration. Empty maps do not satisfy parent acceptance criteria.',
  platformsHeading: 'Persisted platforms',
  platformsSubtitle: 'Reach, uptime, and weekly tick fields as stored — not evaluated outcomes.',
  plansHeading: 'Persisted counter-memetic plans',
  plansSubtitle: 'Lore, distributor, uptake, and elapsed propagation weeks as stored.',
  ownersHeading: 'Persisted content owners',
  ownersSubtitle: 'Incentive fields as stored — resistance outcomes are not computed here.',
  mediaCasesHeading: 'Persisted post-case media cases',
  mediaCasesSubtitle:
    'Containment and artifact inventory as stored — residual risk is not computed here.',
  labelColumn: 'Label',
  viewCountColumn: 'View count',
  uptimeColumn: 'Uptime',
  reachColumn: 'Reach factor',
  tickColumn: 'Last tick week',
  loreColumn: 'Lore state',
  distributorColumn: 'Distributor',
  uptakeColumn: 'Uptake',
  propagationColumn: 'Elapsed weeks',
  incentivesColumn: 'Incentives',
  containmentColumn: 'Local containment',
  riskThresholdColumn: 'Risk threshold',
  mediaArtifactsColumn: 'Media artifacts',
  weeklyDeltaPrefix: 'Weekly delta:',
  availableReachPrefix: 'Available reach:',
  requiredWeeksPrefix: 'Required:',
}

export const SPE_956_PROPAGATION_GRAPH_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Propagation graphs',
  pageSubtitle:
    'Read-only operations view over persisted SPE-956 propagation graph records — authored nodes, edges, and week-close orchestration fields.',
  backToDeskLabel: 'Back to Operations Desk',
  graphsLabel: 'Graph records',
  nodesLabel: 'Total nodes',
  edgesLabel: 'Total edges',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Labels mirror hydrated GameState fields only. This surface does not re-run graph compose or SPE-947 evaluators or invent parent acceptance evidence.',
  emptyTitle: 'No propagation graph records',
  emptyBody:
    'Persisted SPE-956 propagation graph records will appear here after hydration. Empty maps do not satisfy parent acceptance criteria.',
  seedNodePrefix: 'Seed node:',
  elapsedWeeksLabel: 'Elapsed propagation weeks',
  weeklyDeltaLabel: 'Weekly elapsed delta',
  lastTickWeekLabel: 'Last tick week',
  nodesHeading: 'Persisted nodes',
  edgesHeading: 'Persisted edges',
  edgeEmptyLabel: 'Persisted edges empty',
  edgeEmptyBody: 'No persisted edges are authored for this graph.',
  labelColumn: 'Label',
  kindColumn: 'Node kind',
  entityColumn: 'Entity id',
  edgeIdColumn: 'Edge id',
  fromNodeColumn: 'From node',
  toNodeColumn: 'To node',
  spreadFactorColumn: 'Spread factor',
}

export const SPE_956_PARTICIPATORY_CHANNEL_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Participatory channels',
  pageSubtitle:
    'Read-only operations view over persisted SPE-956 participatory channel maps — survivor registries, memory channels, hotlines, async surfaces, and advisory bodies.',
  backToDeskLabel: 'Back to Operations Desk',
  totalChannelsLabel: 'Total channel records',
  survivorRegistriesLabel: 'Survivor registries',
  collectiveMemoryLabel: 'Memory channels',
  hotlinesLabel: 'Hotline channels',
  asyncDiscussionsLabel: 'Async surfaces',
  communityAdvisoryLabel: 'Advisory bodies',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Labels mirror hydrated GameState fields only. This surface does not re-run SPE-2620–2631 evaluators or invent parent acceptance evidence.',
  emptyTitle: 'No participatory channel records',
  emptyBody:
    'Persisted SPE-956 participatory channel records will appear here after hydration. Empty maps do not satisfy parent acceptance criteria.',
  survivorRegistryHeading: 'Survivor informal registry',
  collectiveMemoryHeading: 'Collective memory channel',
  hotlineHeading: 'Hotline channel',
  asyncDiscussionHeading: 'Async discussion surface',
  communityAdvisoryHeading: 'Community advisory body',
  recognitionStanceLabel: 'Recognition stance',
  catalogRuleLabel: 'Catalog rule',
  supportKnowledgeBandLabel: 'Support knowledge band',
  credibilityCeilingLabel: 'Credibility ceiling',
  narrativeStanceLabel: 'Narrative stance',
  recallWindowLabel: 'Recall window',
  stabilizationRuleLabel: 'Stabilization rule',
  scriptQualityLabel: 'Script quality',
  staffingCapacityLabel: 'Staffing capacity',
  languageSupportLabel: 'Language support',
  escalationRulesLabel: 'Escalation rules',
  unansweredModeLabel: 'Unanswered mode',
  angerModeLabel: 'Anger mode',
  handleThresholdLabel: 'Handle threshold',
  participationWindowLabel: 'Participation window',
  transcriptRetentionModeLabel: 'Transcript retention',
  wideningRuleLabel: 'Widening rule',
  memoryStabilizationLabel: 'Memory stabilization',
  missionLabel: 'Mission',
  membershipRuleLabel: 'Membership rule',
  representedStakeholderClassesLabel: 'Represented stakeholder classes',
  authorizedDecisionScopesLabel: 'Authorized decision scopes',
  influenceThresholdLabel: 'Influence threshold',
  decisionCriteriaLabel: 'Decision criteria',
}

export const PUBLISH_QUEUE_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Publish queue',
  pageSubtitle:
    'Read-only operations view over persisted publish-queue records and execution receipts.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Queue records',
  readyToPublishLabel: 'Ready to publish',
  publishedLabel: 'Published (dry-run)',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Statuses reflect hydrated GameState only. Weekly dry-run execution transitions ready records without real CI or GitHub publish side effects.',
  emptyTitle: 'No publish queue records',
  emptyBody:
    'Persisted publish-queue records will appear here after hydration. Invalid records dropped on hydrate are not shown here.',
  recordsHeading: 'Persisted queue records',
  recordsSubtitle:
    'Ready vs published discrimination uses queue status only — no hidden channel truth.',
  labelColumn: 'Label',
  statusColumn: 'Status',
  artifactColumn: 'Release artifact',
  queuedWeekColumn: 'Queued week',
  hooksColumn: 'Hook counts',
  receiptsHeading: 'Execution receipt ledger',
  receiptsSubtitle:
    'Persisted executor receipts keyed by record and week — hydrated map entries only, no re-validation.',
  totalReceiptsLabel: 'Execution receipts',
  completedDryRunLabel: 'Completed (dry-run)',
  completedLiveLabel: 'Completed (live)',
  rejectedOrSkippedLabel: 'Rejected / skipped',
  receiptsEmptyTitle: 'No execution receipts',
  receiptsEmptyBody:
    'Persisted publish-queue execution receipts will appear here after weekly ticks. Invalid receipts dropped on hydrate are not shown here.',
  receiptLabelColumn: 'Label',
  receiptWeekColumn: 'Execution week',
  receiptOutcomeColumn: 'Outcome',
  receiptModeColumn: 'Mode',
  receiptChannelColumn: 'Channel',
  receiptHooksColumn: 'Hooks',
}

export const DEPARTMENT_WORKSHOP_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Workshop mirror',
  pageHeading: 'Department workshops',
  pageSubtitle:
    'Read-only view over durable workshop slots, queued work, blockers, and completion consequences.',
  backToDeskLabel: 'Back to Operations Desk',
  departmentsLabel: 'Departments',
  activeWorkLabel: 'Active work',
  queuedWorkLabel: 'Queued work',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Values reflect hydrated GameState only. Blockers come from slot capacity and lane membership — not live facility or staff projection.',
  emptyTitle: 'No department workshop activity',
  emptyBody:
    'Persisted workshop snapshots, completion receipts, and unsafe secondary-incident markers will appear here after hydration. Invalid entries dropped on hydrate are not shown.',
  emptyLanesTitle: 'No workshop lanes currently active',
  emptyLanesBody:
    'No department snapshots are in lanes right now. Completion receipts and unsafe consequences still appear below when present.',
  departmentsHeading: 'Workshop lanes by department',
  departmentsSubtitle:
    'Active, queued, and paused work with slot capacity and snapshot-derived blockers.',
  freeSlotsSuffix: 'free slots',
  noBlockersLabel: 'No capacity blockers',
  noWorkItemsLabel: 'No work currently in lanes for this department.',
  workOrderColumn: 'Work order',
  laneColumn: 'Lane',
  taskColumn: 'Task',
  caseColumn: 'Case',
  progressColumn: 'Progress',
  outcomesHeading: 'Completion quality and safety ledger',
  outcomesSubtitle:
    'Stored completion receipt grades only — this surface does not re-grade quality or safety.',
  outcomesEmptyTitle: 'No completion receipts',
  outcomesEmptyBody:
    'Workshop completion outcomes appear here after week-close registration. Invalid receipts dropped on hydrate are not shown.',
  weekColumn: 'Completed week',
  qualityColumn: 'Quality',
  safetyColumn: 'Safety',
  consequencesHeading: 'Unsafe completion consequences',
  consequencesSubtitle:
    'Durable secondary-incident spawn markers joined to unsafe completion receipts.',
  consequencesEmptyTitle: 'No unsafe secondary incidents',
  consequencesEmptyBody:
    'Spawn markers appear here after unsafe completion receipts produce secondary cases.',
  spawnedCaseColumn: 'Spawned case',
}

export const MODIFIABLE_DATA_PACK_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Modifiable data packs',
  pageSubtitle:
    'Read-only operations view over persisted modifiable data-pack records and safe-fail import posture.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Pack records',
  appliedLabel: 'Applied',
  needsRevisionLabel: 'Needs revision',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Records reflect hydrated GameState only. Rejected or invalid payloads dropped on hydrate are not shown here.',
  emptyTitle: 'No modifiable data-pack records',
  emptyBody:
    'Persisted modifiable data-pack records will appear here after hydration. Invalid records dropped on hydrate are not shown here.',
  recordsHeading: 'Persisted pack records',
  recordsSubtitle:
    'Applied vs needs-revision discrimination uses import status only — no hidden validation truth.',
  packIdColumn: 'Pack id',
  statusColumn: 'Import status',
  kindColumn: 'Pack kind',
  schemaColumn: 'Schema version',
  sectionsColumn: 'Sections',
}

export const PATTERN_SOURCE_SERIES_MIRROR_UI_TEXT: Record<string, string> = {
  pageEyebrow: 'Planning mirror',
  pageHeading: 'Pattern source series intake',
  pageSubtitle:
    'Read-only operations view over persisted intake records and readiness-ranked processing queue.',
  backToDeskLabel: 'Back to Operations Desk',
  totalRecordsLabel: 'Persisted records',
  queueEligibleLabel: 'Queue entries',
  pipelineActiveLabel: 'Pipeline active',
  weekLabel: 'Campaign week',
  readOnlyNote:
    'Queue rank follows readiness and CP utility — publication date is a tie-breaker only. Invalid records dropped on hydrate are not shown here.',
  emptyTitle: 'No intake records',
  emptyBody:
    'Persisted pattern source series records will appear here after hydration. This mirror does not re-validate hidden truth.',
  queueHeading: 'Processing queue projection',
  queueSubtitle: 'Ranked by readiness score and CP utility, not publication recency.',
  recordsHeading: 'Persisted records',
  recordsSubtitle:
    'Queue rank column reflects projection rank; raw fields come from hydrated GameState.',
  emptyQueueBody: 'No records currently qualify for queue projection at default policy thresholds.',
  rankColumn: 'Rank',
  queueRankColumn: 'Queue rank',
  titleColumn: 'Title',
  readinessColumn: 'Readiness',
  utilityColumn: 'CP utility',
  statusColumn: 'Processing status',
  familyColumn: 'Source family',
  publicationColumn: 'Publication order',
  editorialColumn: 'Editorial status',
  domainsColumn: 'Domain hints',
}

export const RUN_TRANSFER_TEXT: Record<string, string> = {
  panelSubtitle:
    'Export the current run, import a prior run payload, or start fresh from the current balance setup.',
  payloadLabel: 'Run payload',
  payloadPlaceholder: 'Paste a Containment Protocol run export here.',
  exportRun: 'Export Run',
  importRun: 'Import Run',
  newRunFromCurrentConfig: 'New Run From Current Config',
  clearPayload: 'Clear payload',
  invalidPayload: 'Run payload is not valid for this build.',
}

/**
 * Shared shell and fallback copy.
 */
export const SHELL_UI_TEXT: Record<string, string> = {
  agentNotFoundTitle: 'Agent Not Found',
  caseNotFoundTitle: 'Case Not Found',
  teamNotFoundTitle: 'Team Not Found',
  reportNotFoundTitle: 'Report Not Found',
  intelNotFoundTitle: 'Intel Not Found',
  mvpSystems: 'MVP Systems',
  futureExpansion: 'Future Expansion',
  futureExpansionHint: 'These surfaces read live state but stay outside the MVP command loop.',
  futureBoundaryBadge: 'Future expansion surface',
  futureBoundaryNote:
    'This route is intentionally separated from the MVP gameplay loop. It can evolve without blocking core operations.',
  agentNotFoundMessage: 'The requested agent is not present in the current roster.',
  caseNotFoundMessage: 'The requested operation is not present in the current state.',
  teamNotFoundMessage: 'The requested response unit is not present in the current state.',
  reportNotFoundMessage: 'The requested weekly report is not present in the current state.',
  intelNotFoundMessage: 'The requested template is not present in the active intel catalog.',
  backToTemplate: 'Back to {label}',
  none: 'None',
}

/**
 * @deprecated Use `createDeterministicReportNote` from `domain/reportNotes` directly.
 */
let legacyNoteSequence = 0

export function createNote(content: string, rng?: () => number, timestamp?: number) {
  const baseTimestamp = timestamp ?? Date.now()
  legacyNoteSequence += 1
  const sequence = rng
    ? Math.max(0, Math.trunc(rng() * 1_000_000)) + legacyNoteSequence
    : legacyNoteSequence

  return createDeterministicReportNote(content, 1, sequence, baseTimestamp)
}

/**
 * Simulation event note builders.
 */
export const SIM_NOTES = {
  resolved: (title: string) => formatResolvedCaseNoteContent(title),
  partial: (title: string) => formatPartialCaseNoteContent(title),
  failed: (title: string, stage: number) => formatFailedCaseNoteContent(title, stage),
  deadline: (title: string, stage: number) => formatEscalatedCaseNoteContent(title, stage),
  weekDelta: (delta: number) => formatWeekDeltaNoteContent(delta),
  spawnFollowUp: (count: number) => formatSpawnFollowUpNoteContent(count),
  convertedToRaid: () => formatRaidConvertedNoteContent(),
}

/**
 * Lore stubs for seeded case templates.
 */
export const CASE_LORE_STUBS: Record<string, string> = {
  'chem-001':
    'Archive mention: Sector 7 handled precursor compounds tied to the sealed Meridian Incident.',
  'bio-001':
    'Archive mention: Sub-Level 3 was mothballed after unauthorized tissue-growth trials 14 years ago.',
  'info-001':
    'Archive mention: Node Gamma relay keys were rotated early, suggesting an internal compromise.',
  'combat-001':
    'Archive mention: Perimeter signatures match a disbanded private unit with prior blacksite ties.',
  'escalation-001':
    'Archive mention: Sector 9 contamination mirrors waveforms seen before the Harrow Quarantine.',
  'raid-001':
    'Archive mention: Site Gamma has never reached full-breach status in surviving Directorate records.',
  'escalation-psi-002':
    'Archive mention: Lower-archive cognitive breach logs were sealed after responders began sharing identical false memories across shifts.',
  combat_vampire_nest:
    'Archive mention: Stockyard disappearances track a pre-Protocol burn ledger marked Night Harvest.',
  puzzle_whispering_archive:
    'Archive mention: The university stacks were sealed twice before, each time after faculty memory collapse.',
  mixed_eclipse_ritual:
    'Archive mention: Riverfront eclipse rites correlate with three prior blackout clusters in sealed civic reports.',
  followup_missing_persons:
    'Archive mention: Missing-person spikes usually precede a nest relocation or witness-harvesting cycle.',
  followup_feeding_frenzy:
    'Archive mention: Frenzy clusters are logged as urban animal attacks in every surviving cover report.',
  followup_false_memories:
    'Archive mention: False-memory outbreaks tend to erase the first credible witness inside 48 hours.',
  followup_campus_outbreak:
    'Archive mention: Campus incidents escalate fastest when archive basements and dorm utility tunnels overlap.',
  followup_blackout:
    'Archive mention: Ritual blackouts leave the same copper-burn pattern in substations across three cities.',
  followup_targeted_abductions:
    'Archive mention: Targeted abductions usually indicate the cult has identified the active investigation lead.',
  'ops-001':
    'Archive mention: Dead relay traffic often masks a second listener buried inside abandoned civic hardware.',
  'ops-002':
    'Archive mention: Contradictory witness clusters are a known precursor to directed memory tampering events.',
  'ops-003':
    'Archive mention: Records vault lockouts usually happen after internal chain-of-custody tampering, not hardware failure.',
  'ops-004':
    'Archive mention: Panic briefings have triggered two prior Directorate exposure scares during municipal unrest.',
  'ops-005':
    'Archive mention: Black chamber telemetry was first cataloged during a failed reliquary transfer under seal.',
  'ops-006':
    'Archive mention: Residue checks routinely uncover containment leaks that never appear in official medical logs.',
  'ops-007':
    'Archive mention: Closed hearings tied to occult testimony have a documented pattern of witness substitution attempts.',
  'ops-008':
    'Archive mention: Cold-chain anomalies first appeared in procurement audits following a sealed municipal decommission order.',
  'ops-009':
    'Archive mention: Evidence warehouse quarantines are usually preceded by tampered custody manifests and scrubbed access logs.',
  'ops-critical-staffing':
    'Archive mention: Multi-shift response failures usually begin with silent staffing gaps long before any public-facing containment breach is logged.',
  'reward-mixed-bundle':
    'Archive mention: Recovery bundles that mix funding, material access, and research priority were historically used to mask high-risk salvage operations.',
  'bio-forensics-001':
    'Archive mention: Forensics-lab contamination chains were historically linked to mislabeled biohazard evidence returns.',
  'cyber-raid-001':
    'Archive mention: Cyber-raid cascades have repeatedly originated from emergency relay firmware pushed during citywide outages.',
  'anomaly-raid-001':
    'Archive mention: Anomaly raid sites show matching anchor-glyph geometry to prior mass-containment breach rehearsals.',
  'extraction-raid-001':
    'Archive mention: Extraction-raid signatures align with blacksite transfer attempts aborted after perimeter compromise warnings.',
  'occult-001':
    'Archive mention: Black candle congregations were suppressed twice before under separate chapel renovation orders.',
  'occult-002':
    'Archive mention: Memorial echo incidents tend to reuse the same seven names, regardless of city or decade.',
  'occult-003':
    'Archive mention: Delayed reflections usually indicate a possession line anchored to polished public glass.',
  'occult-004':
    'Archive mention: Ash-reactive reliquaries were removed from open doctrine after the Saint Gall breach.',
  'occult-005':
    'Archive mention: Weather-responsive chapels only appear in files connected to greenhouse burial experiments.',
  'occult-006':
    'Archive mention: Red lantern processions recur in Directorate files whenever a crowd is being used as cover.',
  'occult-007':
    'Archive mention: Crypt-bell incidents were archived as structural tremors until vow-compulsion patterns appeared in responder transcripts.',
  'occult-008':
    'Archive mention: Litany-driven civilian route events historically coincide with shrine-district convergence attempts.',
  'psi-001':
    'Archive mention: Precognitive bleed clusters were first logged around transport hubs 36 hours before confirmed casualty events.',
  'psi-002':
    'Archive mention: Compulsion-network callers historically present as low-profile civilians with no detectable prior psychic training.',
  'psi-003':
    'Archive mention: Memory excision signatures match a redacted witness-protection collapse referenced only as Protocol Echo-14.',
  'psi-occ-001':
    'Archive mention: Hybrid ritual-resonance circles were previously contained only after simultaneous symbol break and medium anchoring.',
  'psi-004':
    'Archive mention: Station-class psionic amplifiers were mothballed under telecom decommission orders after the Null Broadcast hearings.',
  'psi-005':
    'Archive mention: Cascade resonance events become irreversible once node severance attempts are staggered instead of synchronized.',
  'psi-006':
    'Archive mention: Reliquary memory drift artifacts have repeatedly referenced sealed Directorate operations absent from central archives.',
  followup_psi_aftermath:
    'Archive mention: Psychic residue zones usually seed a second bleed if boundary pockets remain active past one operational cycle.',
  'psi-007':
    'Archive mention: Exchange-floor dream incidents were once misfiled as panic contagion until psionic carrier traces were identified.',
}

/**
 * Game-over reasons.
 */
export const GAME_OVER_REASONS: Record<string, string> = {
  breachState: 'Breach threshold crossed. Containment protocol failed.',
  capExceeded: 'Active case capacity exceeded. Directorate overwhelmed.',
  allResolved: 'All active operations concluded. Directorate stands down.',
}

/**
 * Dashboard guidance shown when the simulation is halted.
 */
export const DASHBOARD_HALT_GUIDANCE: Record<string, { title: string; action: string }> = {
  [GAME_OVER_REASONS.breachState]: {
    title: 'Containment breach detected',
    action:
      'Review high-stage cases, then reset to re-run with safer staffing and escalation control.',
  },
  [GAME_OVER_REASONS.capExceeded]: {
    title: 'Case capacity exceeded',
    action:
      'Resolve pressure faster by prioritizing at-risk operations and maintaining reserve team coverage.',
  },
  [GAME_OVER_REASONS.allResolved]: {
    title: 'Run completed successfully',
    action: 'Export this run or reset to start a fresh scenario with adjusted balance settings.',
  },
  default: {
    title: 'Simulation halted',
    action: 'Review the latest report, then reset the run to continue operations.',
  },
}

/**
 * Test contract labels: exact rendered text for status and assignment indicators.
 * These are used by tests to safely match UI text without brittleness from hardcoded regexes.
 */
export const TEST_CONTRACTS = {
  // Case status line rendering: "Status: {label}"
  caseStatus: (status: CaseStatus) => `${CASE_UI_LABELS.status}: ${STATUS_LABELS[status]}`,
  // Case assignment line rendering: "Assigned: {team names}" or just the label for unassigned marker
  caseAssignmentLabel: CASE_UI_LABELS.assigned,
  caseAssignmentTo: CASE_UI_LABELS.assignedTo,
  caseUnassignedMarker: CASE_UI_LABELS.unassigned,
}
